from google.adk.agents import Agent
from pydantic import BaseModel, Field

from researcher_agent.callbacks.callbacks import save_agent_output

MODEL_ID = "gemini-2.5-flash"

SCENE_BREAKDOWN_PROMPT = """
Based on the following script, break it down into multiple scenes sequentially.
Each scene should correspond to a logical part of the script, suitable for a short video segment (e.g., 5-10 seconds).
The output should be a list of strings, where each string is the text for one scene.


# Output format
[
"Text for Scene 1 goes here",
"Text for Scene 2 goes here",
"Text for Scene 3 goes here",
...
"Text for Scene N goes here"
]


# Script generated by the script writer agent:
{script}
"""


class SceneBreakdownAgentOutput(BaseModel):
    scenes: list[str] = Field(
        description="A list of strings, where each string is the text for a scene from the script."
    )


scene_breakdown_agent = Agent(
    name="SceneBreakdownAgent",
    description="Breaks down a video script into a sequence of scenes.",
    instruction=SCENE_BREAKDOWN_PROMPT,
    model=MODEL_ID,
    include_contents="none",
    output_key="scenes",
    output_schema=SceneBreakdownAgentOutput,
    after_agent_callback=save_agent_output,
)
